name: pptx-summarizer-api

services:
  app:
    image: fungi5163/pptx-summarizer-api
    ports:
      - "8000:8000"
    env_file:
      - /root/env/pptx-summarizer-api/.env
    restart: unless-stopped
